### ISSUE TITLE
Parsing tapper generated json logs throws an exception

### ISSUE THREAD

**Issue by indrekj** [Financial-Times/tapper#15]
By default Tapper Trace IDs are encoded to json as an object `{"value":[169513317762981674876240685479724028020,25469]}`. Such object can't be parsed by Fluentd (the number is too long, `Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (13237579633808872962) out of range of long (-9223372036854775808 - 9223372036854775807)`) and log messages are being discarded massively.

As a workaround we have been adding this to our projects:
```
# Proper JSON encoding of TraceId generated by Tapper
for protocol <- [Poison.Encoder, Jason.Encoder] do
  defimpl protocol, for: Tapper.TraceId do
    def encode(trace, options) do
      trace
      |> String.Chars.to_string()
      |> @protocol.encode(options)
    end
  end
end
```

TraceId seems to be put to metadata in https://github.com/Financial-Times/tapper/blob/master/lib/tapper/tracer.ex#L139 . Would it make more sense to use `to_hex` and make it usable with different loggers and parsers?

**Comment by ellispritchard** [comment]
Really, this should be a string anyway, certainly the Zipkin Spans API 2.0 treat the trace-id, and span-id, as strings. Javascript only supports integers up to 2^53 - 1, so JSON encoding either of these as numbers is problematic.

Ideally, it's a string all the way through the stack though, because conversion is expensive.

(I'm not sure what the interaction with Fluentd is, and we had no problems with this at the FT (kubernetes + fluentd, going into Splunk), but then we weren't logging the Tapper.Id as JSON either, and I guess that's your problem).

I need to revive my work on supporting Zipkin Spans API 2.0...

**Comment by ellispritchard** [comment]
@indrekj Please check your code with Tapper 0.6.0 - the representation has changed so I don't believe this work-around should be necessary any more.

**Comment by ellispritchard** [comment]
Closing as presumed fixed - please reopen if necessary.
