### ISSUE TITLE
Post-fact sampling

### ISSUE THREAD

**Issue by ellispritchard** [Financial-Times/tapper#5]
Tracing in Tapper is cheap since the instrumented code is basically just sending a message or two (erm, I should probably write some benchmarks), so it's no biggie if we trace everything and then choose to report some of it.

Sampling is currently only available via the Plug integration, i.e. it's not even in the core Tapper library, because it's done up-front when the request comes in.

Adding a post-fact sampling stage to Tapper would allow some module to be called before sending a trace to the Reporter, which could then see if the trace was 'interesting' enough to sample.

This might include a default "have I sent 10% of traces in the last minute" to maintain current behaviour, but also could *somehow* categorise spans by annotations or span duration, and spot anomalies.

Adding the 'hook' is easy, implementing something that actually generically useful that does the sampling on anything other than a percentage basis is a bit harder. Would be good anyway for a general way of dynamically turning up (or down) the percentage of reported spans.

This could be implemented at current using 'debug' mode and a custom `Reporter`, but would be better to add this as a separate concern (we need a batching `Reporter` implementation ideally anyway, so don't want to complicate that).

**Comment by adriancole** [comment]
after-the-fact sampling has some implications, especially since a decision
to sample is carried with downstream requests, as sampling is most often a
trace-level function. For example, to sample or not is done once, at the
root of the trace, the first request.

In dapper-like-tracing, before-the-fact gives you a consistent decision per
trace, so for example, if you make 3 remote child spans, then 3 more, all
receivers see the same sampling status. Honoring that ensures a trace isn't
confusing operators by having incomplete data.

There's a couple ways to think about late decisions fitting even
considering above.

1. If the desire is to limit span count/trace, consider this a
"span-scoped" functionality. For example, you can use brave's
span.abandon() to drop a span that would clutter a sampled trace
2. if there's a monolith, late trace sampling is of no importance, because
trace headers with sampled status never leave the process (because it is a
monolith!)

Then, there's the idea of calling user functions to teach a trace-level
sampler. For example, you could collect locally spans and feedback their
span.duration into a latency function. This could teach your trace-level
sampler to be adaptive, for example increasing the samples of a particular
endpoint without needing a remote host to coordinate this information.

This is something opencensus do, and brave might do in the future
https://github.com/openzipkin/brave/issues/444

**Comment by ellispritchard** [comment]
Yes, after our discussions, this is something that I've realised is much more complicated than it appears at first sight!

In my GraphQL server use-case, clients are (at least currently) not sending us a trace context, so we are always the decision-making point for sampling. As you suggest, we could use any recent increased latency of downstream services as a hint to dial-up the sampling rate for traces touching those services. Whilst increasing the sampling rate may well degrade overall through-put, it is hopefully less overhead than what is being added by whatever is causing the increase in latency (although there is a potential positive feed-back danger here!).

I also like Census's idea of keeping more spans locally than sent, and allowing a 'UI' view in to these, and other stats, via the node itself, without bogging down the trace collector.
